### ISSUE TITLE
coderd replicas is showing blank despite other data from replicas

### ISSUE THREAD

**Issue by bpmct** [coder/observability#13]
Happy to troubleshoot this live

<img width="1490" alt="Screenshot 2024-05-30 at 6 22 50 PM" src="https://github.com/coder/observability/assets/22407953/ea35f3a2-74c5-4cef-b86b-84b6ed1fcc89">

**Comment by bpmct** [comment]
User error: I didn't deploy the Coder helm chart with 

```yaml
coder:
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '2112'
```
